### ISSUE TITLE
Лаб2 @nkgupta16

### ISSUE THREAD

**Issue by ananasn** [nkgupta16/NKLab2#1]
Отличная работа! Вижу вы постарались и сделали все варианты :)
Рекомендации:
1. Побольше используйте функции. Можно было бы не переписывать код для каждого варианта, а сделать универсальную функцию. Например,
```python3
def add_plot(func, pos, title='y(x)'):
    x = np.linspace(-10, 10, 100)
    y = func(x)
    axs[pos].plot(x, y)
    axs[pos].set_title(title)

# Creating subplots
fig, axs = plt.subplots(5, 2, figsize=(10, 15))

add_plot(lambda x: x**2, (0, 0), 'y=x^2')
add_plot(lambda x: 2*x + 3, (0, 1), 'y= 2x + 3')\

...
```

2. Постарайтесь поменьше использовать магические числа, лучше создавать именованные константы в начале файла. Это улучшает читаемость. Например
```python3
# Sample size
START = -10
STOP = 10
NUM = 100

np.linspace(START, STOP , NUM)
```

Работа принята. За объем выполненной работы я добавляю +4 дополнительных балла.

**Comment by nkgupta16** [comment]
Спасибо за рекомендации! Я внес изменения в код, теперь он короче и более читаемый. 
Также спасибо за дополнительные баллы и за принятие работы.
